"""empty message

Revision ID: 814f6fb02f7d
Revises: aef6fa367d71
Create Date: 2026-03-27 13:55:45.841859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814f6fb02f7d'
down_revision = 'aef6fa367d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
